[package]
name = "snake"
version = "0.1.0"
edition = "2021"
author = "Tom Walter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.130.0"
rand = "0.7.3"